        report.pdf: report.pdf
            gcc report.pdf.c -o report.pdf

        clean:
            rm -f report.pdf
        hello: report.doct
            gcc report.doct.c -o report.doct

        clean:
            rm -f report.doct
